### ISSUE TITLE
Not working in Brave browser

### ISSUE THREAD

**Issue by lev-losenkov** [RobRendell/gTove#54]
It is not possible to join the table by the link.

(OS Windows 10/ Brave Browser v 1.47.171)
![error](https://user-images.githubusercontent.com/105035034/213909542-13be3449-d65b-4589-a262-37e97ea206d3.png)

Error text:

> Error: Error creating WebGL context.

    at new Iu (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:392142)
    at Ze (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:849882)
    at f.width.f.height.m.createElement.set (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:839820)
    at https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:840218
    at fs (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:2976834)
    at Zu (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:2994007)
    at t.unstable_runWithPriority (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:3019326)
    at Xi (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:2935759)
    at ku (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:2990742)
    at Iu (https://illuminantgames.com/gtove/static/js/2.a2fc3973.chunk.js:2:2986828)

**Comment by RobRendell** [comment]
Hi!  That's an error from the underlying 3D library I'm using (three.js), saying that it can't find/access your 3D hardware.

You say you're using Brave Browser, which is a browser I don't support/test on... can you navigate to https://get.webgl.org/ and see whether your browser works there?
 
There are various suggestions for tweaking browser settings to get three.js working in these threads - while they're not talking about Brave Browser, it may have equivalent settings.

https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome

https://github.com/mrdoob/three.js/issues/4927

If those don't help, you might have to use Firefox or Chrome to get it to work, sorry.
